### ISSUE TITLE
DPI value?

### ISSUE THREAD

**Issue by cmahnke** [olokelo/jxlpy#30]
Usually Pillow plugins provide some metadata in the `info`, `dpi` for example - this value is missing for `jxlpy`. Is there another way to get this information?

**Comment by cmahnke** [comment]
Ok, actually I was a bit shocked to learn that JXL doesn't bother to provide even the required infrastructure, see:
* https://github.com/libjxl/libjxl/issues/817
* https://github.com/libjxl/libjxl/issues/3533

Not sure how to proceed, since this means I can't use JXL for easy creation of PDF...

**Comment by olokelo** [comment]
I think in this case the best solution would be to use Exif tags however doing that in jxlpy is not yet supported.
If it's possible in your workflow you could probably use Exiftool [as described here](https://exiftool.org/forum/index.php?topic=2164.0).
I might add Exif support to jxlpy in the future as I already implemented it for the [internal Pillow Plugin](https://github.com/python-pillow/Pillow/pull/7848).

**Comment by cmahnke** [comment]
Ok, thanks - I was afraid that this might be the outcome...

Should I keep this issue open as a remainder? 
Do you plan to abandon this (the project), after your PR has been merged?

**Comment by olokelo** [comment]
I don't have plans on abandoning this project, maybe just removing the Pillow plugin if it would already be in the upstream. High bit depths are not well supported in Pillow so using jxlpy would still make sense for that case, also there's JPEG lossless recompression feature although it's also not yet supported here.

I would encourage to still use Pillow plugin if you only need decoding support of 8 bit images since it's better written and doesn't have Cython dependency.

I will close the issue for now, feel free to reopen if you ever need to :)
